### ISSUE TITLE
Implement PSR-11 in our InstanceCreator class

### ISSUE THREAD

**Issue by JesusValeraDev** [gacela-project/resolver#1]
# 📚 Description

We should implement the [PSR-11](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-11-container.md) to allow people to use our package where we "compromise" to follow the `PHP Standard Recommendation`.

Frameworks like [Laravel](https://laravel.com/docs/10.x/container#psr-11) or [Symfony](https://github.com/symfony/symfony-docs/blob/6.2/components/dependency_injection.rst#the-dependencyinjection-component) already do.

**Comment by Chemaclass** [comment]
What exactly is what you are proposing here? Sorry, I didn't understand the goal by reading the issue description :)

**Comment by JesusValeraDev** [comment]
What I mean is we are doing a `Container Interface` class which resolves dependencies, and there is already a `PSR` in place for this kind of task in PHP which is the [PSR-11](https://www.php-fig.org/psr/psr-11/), I think we should implement that interface in our class to follow the standards.
